### ISSUE TITLE
Cannot compile SUSE Leap 15.3

### ISSUE THREAD

**Issue by unclebrr** [rrveex/nfe#1]
Hello and thanks for your program!
It's been a long time someone doing something for AF and linux...
Still I have a problem:
`/nfe-master>mkdir build && cd build && cmake .. && make -j
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/lib64/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  CMakeLists.txt:23 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/brr/bin/nfe-master/build/CMakeFiles/CMakeOutput.log".
`
Qt5 Widgets installed
libQt5Widgets.5 5.12.7-4.12.2-x86-64
What am I doing wrong? I'm not a programmer, user only. Can you tell me what and where fo fix?
Thanks for the reply! :)

**Comment by rrveex** [comment]
You need `...-devel` package. It doesn't seem to be in the default repo.

- switch repo: https://en.opensuse.org/SDB:KDE_repositories
- install libQt5Charts5-devel
- install libhidapi-devel

I don't know what effects this will have on your installation

**Comment by unclebrr** [comment]
Installed. It's getting better ;) Now it gives error on "endl"
`/usr/include/qt5/QtCore/qtextstream.h:260:28: note:   ‘endl’
 Q_CORE_EXPORT QTextStream &endl(QTextStream &s);
                            ^~~~
In file included from /usr/include/c++/7/iterator:64:0,
                 from /usr/include/qt5/QtCore/qbytearray.h:53,
                 from /usr/include/qt5/QtCore/qstring.h:49,
                 from /usr/include/qt5/QtCore/qhashfunctions.h:44,
                 from /usr/include/qt5/QtCore/qlist.h:47,
                 from /usr/include/qt5/QtCore/qstringlist.h:41,
                 from /usr/include/qt5/QtGui/qcolor.h:46,
                 from /usr/include/qt5/QtGui/qpen.h:44,
                 from /usr/include/qt5/QtGui/QPen:1,
                 from /usr/include/qt5/QtCharts/qabstractaxis.h:34,
                 from /usr/include/qt5/QtCharts/QAbstractAxis:1,
                 from /usr/include/qt5/QtCharts/qchartview.h:33,
                 from /usr/include/qt5/QtCharts/QChartView:1,
                 from /home/brr/bin/nfe-master/src/chartview.h:4,
                 from /home/brr/bin/nfe-master/src/tfrdialog.h:4,
                 from /home/brr/bin/nfe-master/src/tfrdialog.cpp:1:
/usr/include/c++/7/ostream:590:5: note:   ‘std::endl’
     endl(basic_ostream<_CharT, _Traits>& __os)
     ^~~~
make[2]: *** [CMakeFiles/nfe.dir/build.make:210: CMakeFiles/nfe.dir/src/tfrdialog.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:94: CMakeFiles/nfe.dir/all] Error 2
make: *** [Makefile:101: all] Error 2
`

**Comment by rrveex** [comment]
These are the exact steps I did on a _fresh_ install. I hope it helps. If it doesn't, I'm sorry, I can't debug your installation :/

- Yast software, click on View -> Patterns
- on the left side, select: "Base Development", "C/C++ Development", "Qt5 Development" and install them
- at this point, I got the charts-error, so I did the "switch repo, install charts-dev, install hidapi-dev" things from above (this probably un-installed all Qt I had installed with Yast previously, I don't know, it did "stuff")

Edit: you wrote "installed" and I thought the error was in the build step (install needed stuff -> build -> run).
I fixed something regarding `endl` on older qt5 version, please `git pull` and try to build again

**Comment by unclebrr** [comment]
`/home/brr/bin/nfe-master>mkdir build && cd build && cmake .. && make -j
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/brr/bin/nfe-master/build
Scanning dependencies of target nfe_autogen
[  7%] Automatic MOC and UIC for target nfe
[  7%] Built target nfe_autogen
Scanning dependencies of target nfe
[ 14%] Building CXX object CMakeFiles/nfe.dir/src/mainwindow.cpp.o
[ 21%] Building CXX object CMakeFiles/nfe.dir/src/main.cpp.o
[ 28%] Building CXX object CMakeFiles/nfe.dir/src/profiles.cpp.o
[ 35%] Building CXX object CMakeFiles/nfe.dir/nfe_autogen/mocs_compilation.cpp.o
[ 42%] Building CXX object CMakeFiles/nfe.dir/src/screen.cpp.o
[ 50%] Building CXX object CMakeFiles/nfe.dir/src/controls.cpp.o
[ 57%] Building CXX object CMakeFiles/nfe.dir/src/advanced.cpp.o
[ 64%] Building CXX object CMakeFiles/nfe.dir/src/smartstat.cpp.o
[ 71%] Building CXX object CMakeFiles/nfe.dir/src/chartview.cpp.o
[ 78%] Building CXX object CMakeFiles/nfe.dir/src/powercurvedialog.cpp.o
[ 85%] Building CXX object CMakeFiles/nfe.dir/src/tfrdialog.cpp.o
[ 92%] Building CXX object CMakeFiles/nfe.dir/src/device.cpp.o
[100%] Linking CXX executable nfe
[100%] Built target nfe
`
Now it worked! THANK YOU!

**Comment by unclebrr** [comment]
That was too easy :)
Now GUI opens but it sees no device (tried a few).
99-af.rules file is present.

**Comment by rrveex** [comment]
Please post the output of these 2 commands:
```
ls -l /dev/hidraw*
groups
```

**Comment by unclebrr** [comment]
`ls -l /dev/hidraw*
crw-rw-rw-+ 1 root root 246, 0 дек  4 17:26 /dev/hidraw0`
`groups
root`

**Comment by rrveex** [comment]
Please see my post in the forum and let's keep the discussion there, maybe we'll get some help from maelstrom ;)
