### ISSUE TITLE
eLeaf iStick Power 80W not detected

### ISSUE THREAD

**Issue by soup6020** [rrveex/nfe#3]
I've written the necessary udev rules on Arch Linux, as well as reloaded udev obviously, and the program fails to detect the mod. I have the type C variant. Is it incompatible, or am I doing something wrong? The UPC on the box is `6971365273238`

**Comment by rrveex** [comment]
Sorry, I don't know what an "UPC" is. Also, I don't think anything written on the box will help, I don't know anything about eLeaf.

What ArcticFox version are you running? Are you able to connect with the official ArcticFox configuration utility (on Windows)?

**Comment by soup6020** [comment]
The UPC is the number the barcode represents, basically tells you exactly what product it is. It's not running Arctic Fox yet, my hope was to flash it from this program. I'm not sure if NToolbox detects it yet, I haven't bothered fixing my Windows VM yet.

**Comment by rrveex** [comment]
This tool (in this repo) is for configuring devices already running ArcticFox/RedPanda.
As far as I know, there is no way to flash AF/RP other than in Windows. Please read/ask in the forum (link in the project description).
