### ISSUE TITLE
Building Problem Fedora

### ISSUE THREAD

**Issue by spbisc97** [rrveex/nfe#4]
I'm using Fedora 35
I tried to build but I had to make a few changes in order to make it work:

add:
`#include <cassert>`
to:
[device.h](https://github.com/rrveex/nfe/blob/master/src/device.h)
[profiles.h](https://github.com/rrveex/nfe/blob/master/src/profiles.h)
[screen.h](https://github.com/rrveex/nfe/blob/master/src/screen.h)
[settings.h](https://github.com/rrveex/nfe/blob/master/src/settings.h)

and change 
`qsizetype`
to 
`int`
in
[powercurvedialog.cpp](https://github.com/rrveex/nfe/blob/master/src/powercurvedialog.cpp)
[tfrdialog.cpp](https://github.com/rrveex/nfe/blob/master/src/tfrdialog.cpp)

I'm trying to understand why
I have also tried to compile with Qt Creator in order to be sure to have all dependencies(I'm not really a C++ guy I might be making a lot of mistakes)

Thanks For Your work!

**Comment by spbisc97** [comment]
I have also tried to add a few lines in cmake in order to be sure of using right things

`set(QT_VERSION_MAJOR 5)
Qt${QT_VERSION_MAJOR}::Core`

but it was not helpful

**Comment by rrveex** [comment]
Sorry, I read the issue 3 times and couldn't find out what the issue is :)
Please try to be **a lot** more specific than "building problem".
From "I had to... in order to make it work" I understand that you had a problem but managed to fix it?!

I **_guess_** it is (or was?) a problem with the Qt5 installation on your distribution.

**Comment by spbisc97** [comment]
Sorry for the late reply, 
I was able to build the package only with some changes to the code, adding #include <cassert> to some header files and changing qsizetype into int. But I realized too late that I was building it in a conda Base environment (Python VirtualEnv) and probably in that case it did not have access to some system headers. 

Sorry for the disguise and thanks for your amazing work!
